"""initial schema: teams, players, fixtures

Revision ID: 10190fb3794a
Revises: 
Create Date: 2026-08-17 19:02:19.619045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10190fb3794a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('strength_overall_home', sa.Integer(), nullable=False),
    sa.Column('strength_overall_away', sa.Integer(), nullable=False),
    sa.Column('strength_attack_home', sa.Integer(), nullable=False),
    sa.Column('strength_attack_away', sa.Integer(), nullable=False),
    sa.Column('strength_defence_home', sa.Integer(), nullable=False),
    sa.Column('strength_defence_away', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('team_h_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_h_score', sa.Integer(), nullable=True),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('team_h_difficulty', sa.Integer(), nullable=True),
    sa.Column('team_a_difficulty', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_h_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('web_name', sa.String(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('news', sa.String(), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('selected_by_percent', sa.Float(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('bps', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('ict_index', sa.Float(), nullable=False),
    sa.Column('expected_goals', sa.Float(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=False),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=False),
    sa.Column('expected_goals_per_90', sa.Float(), nullable=False),
    sa.Column('expected_assists_per_90', sa.Float(), nullable=False),
    sa.Column('expected_goals_conceded_per_90', sa.Float(), nullable=False),
    sa.Column('defensive_contribution', sa.Integer(), nullable=False),
    sa.Column('defensive_contribution_per_90', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('fixtures')
    op.drop_table('teams')
    # ### end Alembic commands ###
